package com.example.usecase23;

import java.util.List;

/**
 * Data transfer object containing all dashboard metrics generated by the service.
 */
public record DashboardData(
    int currentUsers,
    int viewEvents,
    double conversionRate,
    double customMetric,
    TimelineData timelineData,
    List<ServiceHealth> serviceHealthList,
    List<Double> responseTimes
) {

    public record TimelineData(
        String timestamp,
        int berlinValue,
        int londonValue,
        int newYorkValue,
        int tokyoValue
    ) {}
}
