# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy ${{ matrix.module }}
    runs-on: ubuntu-latest
    concurrency: deploy-${{ matrix.module }}
    strategy:
      fail-fast: false
      matrix:
        module: [signals, geolocation, page-visibility]
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy . --remote-only --config ${{ matrix.module }}/fly.toml --dockerfile ${{ matrix.module }}/Dockerfile --build-secret proKey="$VAADIN_PRO_KEY"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          VAADIN_PRO_KEY: ${{ secrets.VAADIN_PRO_KEY }}
